import {
	findLocatableStructure,
	formatLocateResult,
	locateAll,
	locateStructure,
	suggestLocatableStructures,
} from "@/code/Generation/StructureLocator";
import { computeSeedAsInt } from "@/code/Generation/WorldSeed";
import { getWorldNameFromUrl, worldSeedFor } from "@/code/World/WorldContext";

// ---------------------------------------------------------------------------
// `!locate` — shared by both chat front-ends.
//
// There are two independent command dispatchers in this game: PlayerHud's chat
// (singleplayer) and NetworkManager's (multiplayer). They are separate because
// multiplayer chat goes through MultiplayerHUD and the server, but they used to
// be separate *implementations* too, and they drifted — `/locate` was added to
// one and reported "Unknown command" in the other. The search itself lives in
// Generation/StructureLocator; this module is the command shape on top of it, so
// both front-ends execute literally the same code.
// ---------------------------------------------------------------------------

/** Search radius, in blocks, when the caller does not specify one. */
export const LOCATE_MAX_DISTANCE = 12000;

export type LocateCommandDeps = {
	/** Search origin in world XZ. */
	originX: number;
	originZ: number;
	/**
	 * Terrain seed STRING, exactly as the world it describes was seeded.
	 *
	 * In multiplayer this must be the server's seed, not the one derived from
	 * the URL: the world is generated by the server, so a client that folded its
	 * own URL seed would search a region grid that does not exist and report
	 * confidently wrong coordinates.
	 */
	seed: string;
	maxDistance?: number;
	/**
	 * Applies the teleport. Omit for a read-only search. Both front-ends
	 * teleport by writing the local player position, which is what `!tp` already
	 * does, so this is consistent with existing behaviour.
	 */
	onTeleport?: (x: number, z: number) => void;
	/** Where replies go — the SP chat log or the multiplayer HUD. */
	reply: (text: string) => void;
};

/**
 * Seed for the world the local player is actually standing in.
 *
 * Multiplayer overrides `serverSeed` with the seed the server reported, because
 * a hosted world is generated from the server's seed rather than from anything
 * derivable from the client's URL.
 */
export function currentWorldSeed(serverSeed: string | null = null): string {
	if (serverSeed !== null) return serverSeed;
	const worldName = getWorldNameFromUrl();
	return worldName === null ? "" : worldSeedFor(worldName);
}

export function runLocateCommand(
	args: string[],
	deps: LocateCommandDeps,
): void {
	const { originX, originZ, reply } = deps;

	if (args.length === 0) {
		reply("Usage: !locate <name> [tp] | !locate all");
		return;
	}

	if (deps.seed === "") {
		reply("No world seed available");
		return;
	}

	const seed = computeSeedAsInt(deps.seed);

	// `all` lists the nearest of everything: the quickest way to see what a
	// seed has around it.
	if (args[0].toLowerCase() === "all") {
		const all = locateAll({
			originX,
			originZ,
			seed,
			maxDistance: deps.maxDistance ?? LOCATE_MAX_DISTANCE,
		});
		if (all.length === 0) {
			reply("No structures found nearby");
			return;
		}
		reply(`Nearest of each structure (${all.length} found):`);
		for (const match of all) {
			reply(
				`  ${match.structure.label}: ${match.x} ${match.z} (${Math.round(match.distance)} blocks)`,
			);
		}
		return;
	}

	// The teleport flag is optional and may appear anywhere in the args.
	const wantsTeleport = args.some((arg) => arg.toLowerCase() === "tp");
	const name = args.find((arg) => arg.toLowerCase() !== "tp") ?? "";

	const structure = findLocatableStructure(name);
	if (!structure) {
		reply(`Unknown structure: ${name}`);
		const suggestions = suggestLocatableStructures(name);
		if (suggestions.length > 0) {
			reply(`Did you mean: ${suggestions.map((s) => s.key).join(", ")}?`);
		} else {
			reply("Try !locate all to list every structure");
		}
		return;
	}

	const match = locateStructure(structure, {
		originX,
		originZ,
		seed,
		maxDistance: deps.maxDistance ?? LOCATE_MAX_DISTANCE,
	});

	if (!match) {
		const limit = deps.maxDistance ?? LOCATE_MAX_DISTANCE;
		reply(`No ${structure.label.toLowerCase()} within ${limit} blocks`);
		return;
	}

	reply(formatLocateResult(match, originX, originZ));

	if (wantsTeleport) {
		if (!deps.onTeleport) {
			reply("Teleporting is not available here");
			return;
		}
		deps.onTeleport(match.x, match.z);
		// Confirm rather than moving the player silently.
		reply(`Teleported to ${match.x} ${match.z}`);
	}
}
