export const GenerationParams = {
  SEED: "my-secret-seed",
  CHUNK_SIZE: 16,
  TERRAIN_SCALE: 0.001,
  OCTAVES: 8,
  PERSISTENCE: 0.31,
  LACUNARITY: 3.3,
  TERRAIN_HEIGHT_BASE: 20,
  TERRAIN_HEIGHT_AMPLITUDE: 333,
  SEA_LEVEL: 42,
  RIVER_SCALE: 1 / 333,
  TEMPERATURE_NOISE_SCALE: 0.000303,
  HUMIDITY_NOISE_SCALE: 0.0002,
  CONTINENTALNESS_NOISE_SCALE: 0.0008,
  EROSION_NOISE_SCALE: 0.002,
  PV_NOISE_SCALE: 0.006,
  RIVER_TUNNEL_THRESHOLD_OFFSET: 6,
  RIVER_TRANSITION_RANGE: 15,
};

export type GenerationParamsType = typeof GenerationParams;
