import { getFinalTerrainHeight } from "../TerrainHeightMap";
import {
	buildMayaTempleLayout,
	computeMayaSealBox,
	MAYA_TEMPLE_HALF_EXTENT,
	type MayaSealBox,
	type MayaTempleLayout,
} from "./MayaTempleLayout";
import { computeRegion, type RegionConfig } from "./RegionFeature";

// ---------------------------------------------------------------------------
// Temple resolution + cave sealing.
//
// The cave carver runs AFTER structures have been written, so a dungeon carved
// by MayaTempleFeature would otherwise be eaten by the cave pass. The fix is
// for the carver to ask "is this voxel inside a temple's protected box?" — and
// the answer has to be derivable from world coordinates alone, because the
// carver and the feature never talk to each other.
//
// Everything below is therefore a pure function of (worldX, worldZ, seed) and
// the same `getFinalTerrainHeight` the feature uses, so both sides independently
// arrive at the same box.
// ---------------------------------------------------------------------------

/**
 * Region config for temple placement. regionSize 8 = 8x8 chunks = 256x256
 * blocks, so temples are rare enough to be landmarks rather than clutter.
 */
export const MAYA_TEMPLE_REGION: RegionConfig = {
	regionSize: 8,
	magicA: 582394117,
	magicB: 296746381,
	spawnChance: 62,
	earlyReturn: false,
	offsetSeedX: 11,
	offsetSeedZ: 23,
};

/**
 * How many chunks around the chunk being generated must be probed for a
 * temple centre. Mirrors STRUCTURE_SEARCH_RADIUS in Terrain/StructurePlacer —
 * a structure is only ever generated by chunks within that radius of its
 * centre chunk, so the seal must probe the same window or sealed chunks would
 * disagree with the carve pass.
 */
const SEAL_SEARCH_RADIUS = 2;

export type ResolvedTemple = {
	templeId: number;
	centerX: number;
	centerZ: number;
};

/**
 * Resolve the Maya temple owning a region, or null when the region holds no
 * temple. Pure: same (chunkX, chunkZ, seed) always yields the same answer.
 */
export function resolveTempleInRegion(
	chunkX: number,
	chunkZ: number,
	chunkSize: number,
	seed: number,
): ResolvedTemple | null {
	const region = computeRegion(
		chunkX,
		chunkZ,
		chunkSize,
		seed,
		MAYA_TEMPLE_REGION,
	);
	if (!region) return null;

	return {
		templeId: region.regionHash,
		centerX: region.centerX,
		centerZ: region.centerZ,
	};
}

/**
 * Build the full layout for a resolved temple.
 *
 * The ground sampler is deliberately the canonical `getFinalTerrainHeight` and
 * not the SurfaceGenerator prepass: this function is also called from the main
 * thread, and only the canonical function is guaranteed to agree across the
 * worker boundary.
 */
export function buildTempleLayout(
	resolved: ResolvedTemple,
	seed: number,
): MayaTempleLayout {
	return buildMayaTempleLayout(
		resolved.templeId,
		seed,
		resolved.centerX,
		resolved.centerZ,
		getFinalTerrainHeight,
	);
}

/** AABB overlap test against a temple's seal box. */
export function sealOverlaps(
	seal: MayaSealBox,
	minX: number,
	minY: number,
	minZ: number,
	maxX: number,
	maxY: number,
	maxZ: number,
): boolean {
	return (
		seal.maxX >= minX &&
		seal.minX <= maxX &&
		seal.maxZ >= minZ &&
		seal.minZ <= maxZ &&
		seal.maxY >= minY &&
		seal.minY <= maxY
	);
}

/** Half-width used when masking a chunk's columns. */
export { MAYA_TEMPLE_HALF_EXTENT };

export type SealColumnMask = {
	/** True when at least one column of the chunk is inside a temple seal. */
	hasSeal: boolean;
	/** Per-column flag, indexed `localX + localZ * chunkSize`. */
	mask: Uint8Array;
	/** Inclusive Y range that is sealed, for the columns flagged in `mask`. */
	minY: number;
	maxY: number;
};

/**
 * Fill `out` with a per-column "this column is inside a temple seal" flag for
 * the chunk at (chunkX, chunkZ), and report the sealed Y range.
 *
 * Probes the same +/-2 chunk window the structure placer uses, so the seal
 * always covers exactly the columns the structure pass would have written.
 */
export function fillSealColumnMask(
	chunkX: number,
	chunkZ: number,
	chunkSize: number,
	seed: number,
	out: Uint8Array,
): SealColumnMask {
	out.fill(0, 0, chunkSize * chunkSize);

	const chunkMinX = chunkX * chunkSize;
	const chunkMaxX = chunkMinX + chunkSize - 1;
	const chunkMinZ = chunkZ * chunkSize;
	const chunkMaxZ = chunkMinZ + chunkSize - 1;

	let minY = Number.POSITIVE_INFINITY;
	let maxY = Number.NEGATIVE_INFINITY;

	// PERF: probe whole REGIONS rather than individual chunks. A temple's centre
	// is derived from its region, so the 5x5 chunk search window resolves to at
	// most 2x2 distinct regions -- 21 of the original 25 probes recomputed an
	// identical answer. Mirrors fillMineshaftSealMask.
	const regionSize = MAYA_TEMPLE_REGION.regionSize;
	const minRegionX = Math.floor((chunkX - SEAL_SEARCH_RADIUS) / regionSize);
	const maxRegionX = Math.floor((chunkX + SEAL_SEARCH_RADIUS) / regionSize);
	const minRegionZ = Math.floor((chunkZ - SEAL_SEARCH_RADIUS) / regionSize);
	const maxRegionZ = Math.floor((chunkZ + SEAL_SEARCH_RADIUS) / regionSize);

	for (let rx = minRegionX; rx <= maxRegionX; rx++) {
		for (let rz = minRegionZ; rz <= maxRegionZ; rz++) {
			// computeRegion derives the region from the CHUNK it is handed, so
			// pass a chunk inside this region, not the region index itself.
			const resolved = resolveTempleInRegion(
				rx * regionSize,
				rz * regionSize,
				chunkSize,
				seed,
			);
			if (!resolved) continue;

			// Cheap box-only path: the full layout (rooms, corridors, ramps,
			// glyphs) is irrelevant here and this runs for every region in range.
			const s = computeMayaSealBox(
				resolved.centerX,
				resolved.centerZ,
				getFinalTerrainHeight,
			);

			if (
				s.maxX < chunkMinX ||
				s.minX > chunkMaxX ||
				s.maxZ < chunkMinZ ||
				s.minZ > chunkMaxZ
			) {
				continue;
			}

			const x0 = Math.max(s.minX, chunkMinX);
			const x1 = Math.min(s.maxX, chunkMaxX);
			const z0 = Math.max(s.minZ, chunkMinZ);
			const z1 = Math.min(s.maxZ, chunkMaxZ);

			for (let wz = z0; wz <= z1; wz++) {
				const localZ = wz - chunkMinZ;
				// PERF: the wx range is contiguous in `out`, so fill the row
				// instead of storing one element at a time.
				out.fill(
					1,
					x0 - chunkMinX + localZ * chunkSize,
					x1 - chunkMinX + localZ * chunkSize + 1,
				);
			}

			if (s.minY < minY) minY = s.minY;
			if (s.maxY > maxY) maxY = s.maxY;
		}
	}

	if (minY > maxY) return sealMaskScratch(false, 0, -1, out);

	return sealMaskScratch(true, minY, maxY, out);
}

// PERF: module-level result scratch. fillSealColumnMask runs once per
// underground chunk and callers only read the fields before the next call, so
// one shared object replaces a fresh literal per chunk.
const _sealResult: SealColumnMask = {
	hasSeal: false,
	mask: new Uint8Array(0),
	minY: 0,
	maxY: -1,
};

function sealMaskScratch(
	hasSeal: boolean,
	minY: number,
	maxY: number,
	mask: Uint8Array,
): SealColumnMask {
	_sealResult.hasSeal = hasSeal;
	_sealResult.mask = mask;
	_sealResult.minY = minY;
	_sealResult.maxY = maxY;
	return _sealResult;
}
