export const GenerationParams = {
	SEED: "my-secret-seed",
	CHUNK_SIZE: 32,
	TERRAIN_SCALE: 0.0008,
	OCTAVES: 2,
	PERSISTENCE: 0.31,
	LACUNARITY: 3.3,
	TERRAIN_HEIGHT_BASE: 20,
	TERRAIN_HEIGHT_AMPLITUDE: 100,
	SEA_LEVEL: 42,
	RIVER_SCALE: 0.001,
	TEMPERATURE_NOISE_SCALE: 0.00003,
	HUMIDITY_NOISE_SCALE: 0.00005,
	CONTINENTALNESS_NOISE_SCALE: 0.000045,
	EROSION_NOISE_SCALE: 0.00015,
	PV_NOISE_SCALE: 0.004,
	RIVER_TUNNEL_THRESHOLD_OFFSET: 6,
	RIVER_TRANSITION_RANGE: 16,

	// Cave generation — 3 noise layers for multi-scale caves
	CAVE_CHEESE_FREQ: 0.01,
	CAVE_TUNNEL_FREQ: 0.025,
	CAVE_DETAIL_FREQ: 0.04,
	CAVE_CHEESE_THRESHOLD: 0.65,
	CAVE_TUNNEL_THRESHOLD: 0.72,
	CAVE_DETAIL_AMPLITUDE: 0.06,
	CAVE_SURFACE_BLEND_UPPER: 128,
	CAVE_SURFACE_BLEND_LOWER: -16,
	CAVE_FULL_DENSITY_DEPTH: -128,
	CAVE_DENSITY_MIN: 0.00001,
	CAVE_DENSITY_MAX: 0.3,
	LAVA_LEVEL: -1600,

	// Ore generation
	ORE_SEARCH_RADIUS_CHUNKS: 2,

	// Aquifer generation
	AQUIFER_FREQ: 0.01,
	AQUIFER_MIN_Y: -256,
	AQUIFER_MAX_Y: -16,
	AQUIFER_THRESHOLD: 0.35,
} as const;

export type GenerationParamsType = typeof GenerationParams;
